export const userFixtures = [
  {
    id: 'admin-demo',
    email: 'admin@beautyshop.test',
    displayName: 'Quản trị BeautyShop',
    role: 'ADMIN' as const,
    passwordEnv: 'SEED_ADMIN_PASSWORD',
    address: {
      id: 'address-admin',
      recipientName: 'Quản trị BeautyShop',
      phone: '0900000001',
      line1: '1 Nguyễn Huệ',
      line2: null,
      ward: 'Bến Nghé',
      district: 'Quận 1',
      province: 'TPHCM',
    },
  },
  {
    id: 'test-customer-1',
    email: 'customer@beautyshop.test',
    displayName: 'Nguyễn Văn A',
    role: 'CUSTOMER' as const,
    passwordEnv: 'SEED_CUSTOMER_PASSWORD',
    address: {
      id: 'default',
      recipientName: 'Nguyễn Văn A',
      phone: '0901234567',
      line1: '123 Đường Lê Lợi',
      line2: null,
      ward: 'Phường Bến Nghé',
      district: 'Quận 1',
      province: 'TPHCM',
    },
  },
  {
    id: 'test-customer-2',
    email: 'customer2@beautyshop.test',
    displayName: 'Trần Minh Anh',
    role: 'CUSTOMER' as const,
    passwordEnv: 'SEED_CUSTOMER2_PASSWORD',
    address: {
      id: 'address-customer-2',
      recipientName: 'Trần Minh Anh',
      phone: '0900000002',
      line1: '20 Bạch Đằng',
      line2: null,
      ward: 'Hải Châu',
      district: 'Hải Châu',
      province: 'Đà Nẵng',
    },
  },
  {
    id: 'demo-customer-3',
    email: 'lethu@beautyshop.test',
    displayName: 'Lê Thu Hà',
    role: 'CUSTOMER' as const,
    // Khách demo bổ sung dùng chung mật khẩu với khách mẫu chính.
    passwordEnv: 'SEED_CUSTOMER_PASSWORD',
    address: {
      id: 'address-customer-3',
      recipientName: 'Lê Thu Hà',
      phone: '0912345678',
      line1: '45 Trần Hưng Đạo',
      line2: null,
      ward: 'Hàng Bài',
      district: 'Hoàn Kiếm',
      province: 'Hà Nội',
    },
  },
  {
    id: 'demo-customer-4',
    email: 'phamkhoa@beautyshop.test',
    displayName: 'Phạm Minh Khoa',
    role: 'CUSTOMER' as const,
    // Khách demo bổ sung dùng chung mật khẩu với khách mẫu chính.
    passwordEnv: 'SEED_CUSTOMER_PASSWORD',
    address: {
      id: 'address-customer-4',
      recipientName: 'Phạm Minh Khoa',
      phone: '0987654321',
      line1: '88 Nguyễn Văn Linh',
      line2: null,
      ward: 'Tân Phong',
      district: 'Quận 7',
      province: 'TPHCM',
    },
  },
  {
    id: 'demo-customer-5',
    email: 'vongoc@beautyshop.test',
    displayName: 'Võ Ngọc Trâm',
    role: 'CUSTOMER' as const,
    // Khách demo bổ sung dùng chung mật khẩu với khách mẫu chính.
    passwordEnv: 'SEED_CUSTOMER_PASSWORD',
    address: {
      id: 'address-customer-5',
      recipientName: 'Võ Ngọc Trâm',
      phone: '0935112233',
      line1: '12 Lý Tự Trọng',
      line2: null,
      ward: 'Tân An',
      district: 'Ninh Kiều',
      province: 'Cần Thơ',
    },
  },
  {
    id: 'demo-customer-6',
    email: 'dangquang@beautyshop.test',
    displayName: 'Đặng Quang Huy',
    role: 'CUSTOMER' as const,
    // Khách demo bổ sung dùng chung mật khẩu với khách mẫu chính.
    passwordEnv: 'SEED_CUSTOMER_PASSWORD',
    address: {
      id: 'address-customer-6',
      recipientName: 'Đặng Quang Huy',
      phone: '0978223344',
      line1: '7 Lê Thánh Tông',
      line2: null,
      ward: 'Máy Tơ',
      district: 'Ngô Quyền',
      province: 'Hải Phòng',
    },
  },
] as const;
